force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/WOO_WMF_Orders__c.object-meta.xml
<CustomObject>
    <description>Object for the orders</description>
    <label>CCC order</label>
    <pluralLabel>CCC orders</pluralLabel>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Order_Previous_Errors__c.field-meta.xml
<CustomField>
    <fullName>WOO_Order_Previous_Errors__c</fullName>
    <description>JSON Used for main free orders</description>
    <label>WOO_Order_Previous_Errors</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/wow/wmf_order/classes/free_order/WOO_freeOrderAgoraFormControllerRepair.cls
public with sharing class WOO_freeOrderAgoraFormControllerRepair {
    public static WOO_WS_Agora_Orders.InterfaceDef webServce = new WOO_WS_Agora_Orders();

    @AuraEnabled(cacheable=false)
    public static WOO_freeOrderAgoraFrontEndDTO.CreateRepairFrontResponse sendMainOrder(
        WOO_freeOrderAgoraFrontEndDTO.SendOrderBase inputOrderBase,
        WOO_freeOrderAgoraFrontEndDTO.SendOrderMain inputOrderMain
    ) {
        webServce.loadApiKey(inputOrderBase.cccGroup);
        WOO_freeOrderAgoraFrontEndDTO.CreateRepairFrontResponse responseFront = new WOO_freeOrderAgoraFormSendRepairService(
                webServce,
                inputOrderBase
            )
            .sendMainOrder(inputOrderMain);
        return responseFront;
    }

    @AuraEnabled(cacheable=false)
    public static WOO_freeOrderAgoraFrontEndDTO.CreateRepairFrontResponse sendGoodwillSparePartsOrder(
        WOO_freeOrderAgoraFrontEndDTO.SendOrderBase inputOrderBase,
        WOO_freeOrderAgoraFrontEndDTO.SendRepairGoodwillSpareParts inputSparePartsOrder
    ) {
        webServce.loadApiKey(inputOrderBase.cccGroup);
        WOO_freeOrderAgoraFrontEndDTO.CreateRepairFrontResponse responseFront = new WOO_freeOrderAgoraFormSendRepairService(
                webServce,
                inputOrderBase
            )
            .sendGoodwillSparePartsOrder(inputSparePartsOrder);
        return responseFront;
    }

    @AuraEnabled(cacheable=false)
    public static WOO_freeOrderAgoraFrontEndDTO.CreateRepairFrontResponse sendGoodwillProductOrder(
        WOO_freeOrderAgoraFrontEndDTO.SendOrderBase inputOrderBase,
        WOO_freeOrderAgoraFrontEndDTO.SendRepairGoodwillProduct inputGoodwillProductOrder
    ) {
        webServce.loadApiKey(inputOrderBase.cccGroup);
        WOO_freeOrderAgoraFrontEndDTO.CreateRepairFrontResponse responseFront = new WOO_freeOrderAgoraFormSendRepairService(
                webServce,
                inputOrderBase
            )
            .sendGoodwillProductOrder(inputGoodwillProductOrder);
        return responseFront;
    }

    @AuraEnabled(cacheable=false)
    public static void savePreviousErrors(String orderId, String errors) {
        PAD.bypassAll = true;
        update new WOO_WMF_Orders__c(Id = orderId, WOO_Order_Previous_Errors__c = errors);
        PAD.bypassAll = false;
    }
}