force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/WOO_WMF_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_Requested_quantity__c.field-meta.xml
<CustomField>
    <fullName>WOO_Requested_quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Requested quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_WMF_Order__c.field-meta.xml
<CustomField>
    <fullName>WOO_WMF_Order__c</fullName>
    <label>CCC Order</label>
    <referenceTo>WOO_WMF_Orders__c</referenceTo>
    <relationshipName>WMF_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/recordTypes/Finished_products_Spare_part.recordType-meta.xml
<RecordType>
    <fullName>Finished_products_Spare_part</fullName>
    <active>true</active>
    <description>Record Type for Finished Product order or Spare Parts order</description>
    <label>Finished products/Spare part</label>
</RecordType>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/recordTypes/Repair.recordType-meta.xml
<RecordType>
    <fullName>Repair</fullName>
    <active>true</active>
    <description>Record Type for Repair order</description>
    <label>Repair</label>
</RecordType>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/WOO_WMF_Orders__c.object-meta.xml
<CustomObject>
    <description>Object for the orders</description>
    <label>CCC order</label>
    <pluralLabel>CCC orders</pluralLabel>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>WOO_Order_Type__c</fullName>
    <defaultValue>&apos;Finished products&apos;</defaultValue>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finished products</fullName>
            </value>
            <value>
                <fullName>Spare part</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
                <label>Spare part and accessories (Free Of Charge)</label>
            </value>
            <value>
                <fullName>FEX</fullName>
                <label>Finish product (Free Exchange)</label>
            </value>
            <value>
                <fullName>Goodwill</fullName>
                <label>Other free order type (goodwill)</label>
            </value>
            <value>
                <fullName>Goodwill_SpareParts</fullName>
                <label>Other free order type (goodwill : Spare Parts)</label>
            </value>
            <value>
                <fullName>Goodwill_Product</fullName>
                <label>Other free order type (goodwill : Product)</label>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/wow/wmf_order/classes/WOO_WMFOrdersLineItemHandler.cls
public with sharing class WOO_WMFOrdersLineItemHandler {
    public static final string REQUESTED_QUANTITY_ERROR_MESSAGE = 'Requested quantity is required for finished product or spare part order type';
    public static final string MISMATCHED_TYPE_ERROR = 'Order and OrderLineItem type doesn\'t match';

    public static void checkIfRequestedQuantityRequired(
        List<WOO_WMF_Order_Line_Item__c> orderLineItems
    ) {
        Map<String, RecordType> recordTypes = CustomMetadataCache.getRecordTypeMapByName();

        for (WOO_WMF_Order_Line_Item__c oli : orderLineItems) {
            if (
                oli.recordTypeId == recordTypes.get('Finished_products_Spare_part').Id &&
                (oli.WOO_Requested_quantity__c == null ||
                oli.WOO_Requested_quantity__c == 0)
            ) {
                oli.addError(REQUESTED_QUANTITY_ERROR_MESSAGE);
            }
        }
    }

    public static void checkIfOrderTypeMatch(List<WOO_WMF_Order_Line_Item__c> orderLineItems) {
        List<Id> ordersId = new List<Id>();
        for (WOO_WMF_Order_Line_Item__c oli : orderLineItems) {
            ordersId.add(oli.WOO_WMF_Order__c);
        }

        Map<String, RecordType> recordTypes = CustomMetadataCache.getRecordTypeMapByName();

        Map<Id, WOO_WMF_Orders__c> orders = new Map<Id, WOO_WMF_Orders__c>(
            [SELECT Id, WOO_Order_Type__c FROM WOO_WMF_Orders__c WHERE Id IN :ordersId]
        );
        for (WOO_WMF_Order_Line_Item__c oli : orderLineItems) {
            if (
                oli.recordTypeId == recordTypes.get('Finished_products_Spare_part').Id &&
                (orders.get(oli.WOO_WMF_Order__c).WOO_Order_Type__c != 'Finished products' &&
                orders.get(oli.WOO_WMF_Order__c).WOO_Order_Type__c != 'Spare part')
            ) {
                oli.addError(MISMATCHED_TYPE_ERROR);
            } else if (
                oli.recordTypeId == recordTypes.get('Repair').Id &&
                orders.get(oli.WOO_WMF_Order__c).WOO_Order_Type__c != 'Repair'
            ) {
                oli.addError(MISMATCHED_TYPE_ERROR);
            }
        }
    }
}