force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/WOO_WMF_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_Comment__c.field-meta.xml
<CustomField>
    <fullName>WOO_Comment__c</fullName>
    <label>Comment</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_Country__c.field-meta.xml
<CustomField>
    <fullName>WOO_Country__c</fullName>
    <defaultValue>IF($User.UserCountryCode__c = &apos;WM&apos;, &apos;DE&apos;, $User.UserCountryCode__c)</defaultValue>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_Product_CMMF__c.field-meta.xml
<CustomField>
    <fullName>WOO_Product_CMMF__c</fullName>
    <formula>WOO_Product__r.CMMF__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product CMMF</label>
    <type>Text</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_Requested_quantity__c.field-meta.xml
<CustomField>
    <fullName>WOO_Requested_quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Requested quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_WMF_Order__c.field-meta.xml
<CustomField>
    <fullName>WOO_WMF_Order__c</fullName>
    <label>CCC Order</label>
    <referenceTo>WOO_WMF_Orders__c</referenceTo>
    <relationshipName>WMF_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/WOO_WMF_Orders__c.object-meta.xml
<CustomObject>
    <description>Object for the orders</description>
    <label>CCC order</label>
    <pluralLabel>CCC orders</pluralLabel>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Case__c.field-meta.xml
<CustomField>
    <fullName>WOO_Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>CCC orders</relationshipLabel>
    <relationshipName>WMF_Order</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Commercial_organization__c.field-meta.xml
<CustomField>
    <fullName>WOO_Commercial_organization__c</fullName>
    <label>Commercial organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>K101</fullName>
                <default>true</default>
                <label>K101</label>
            </value>
            <value>
                <fullName>K109</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_CPD_client_code__c.field-meta.xml
<CustomField>
    <fullName>WOO_CPD_client_code__c</fullName>
    <label>CPD client code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>WOO_Commercial_organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>98001019</fullName>
                <default>true</default>
                <label>CKW End user Germany K101</label>
            </value>
            <value>
                <fullName>98001020</fullName>
                <label>CKW End user Austria K101</label>
            </value>
            <value>
                <fullName>98001103</fullName>
                <label>SDA End user Germany K101</label>
            </value>
            <value>
                <fullName>98001120</fullName>
                <label>SDA End user Austria K101</label>
            </value>
            <value>
                <fullName>98001102</fullName>
                <label>SDA Traders Germany K101</label>
            </value>
            <value>
                <fullName>98001030</fullName>
                <label>CKW End user inside Europe K109</label>
            </value>
            <value>
                <fullName>98001111</fullName>
                <label>SDA End user inside Europe K109</label>
            </value>
            <value>
                <fullName>98001113</fullName>
                <label>SDA Traders inside Europe K109</label>
            </value>
            <value>
                <fullName>98001021</fullName>
                <isActive>false</isActive>
                <label>98001021</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Is_File_Created__c.field-meta.xml
<CustomField>
    <fullName>WOO_Is_File_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to check if the file has been created in azure storage</description>
    <label>Is File Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>WOO_Order_Type__c</fullName>
    <defaultValue>&apos;Finished products&apos;</defaultValue>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finished products</fullName>
            </value>
            <value>
                <fullName>Spare part</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
                <label>Spare part and accessories (Free Of Charge)</label>
            </value>
            <value>
                <fullName>FEX</fullName>
                <label>Finish product (Free Exchange)</label>
            </value>
            <value>
                <fullName>Goodwill</fullName>
                <label>Other free order type (goodwill)</label>
            </value>
            <value>
                <fullName>Goodwill_SpareParts</fullName>
                <label>Other free order type (goodwill : Spare Parts)</label>
            </value>
            <value>
                <fullName>Goodwill_Product</fullName>
                <label>Other free order type (goodwill : Product)</label>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Requested_delivery_date__c.field-meta.xml
<CustomField>
    <fullName>WOO_Requested_delivery_date__c</fullName>
    <label>Requested delivery date</label>
    <type>Date</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Requested_delivery_date_sap_format__c.field-meta.xml
<CustomField>
    <fullName>WOO_Requested_delivery_date_sap_format__c</fullName>
    <formula>TEXT(YEAR(WOO_Requested_delivery_date__c)) &amp; 
IF(AND(MONTH(WOO_Requested_delivery_date__c)&gt;0,MONTH(WOO_Requested_delivery_date__c)&lt;9),TEXT(0)&amp;TEXT(MONTH(WOO_Requested_delivery_date__c)),TEXT(MONTH(WOO_Requested_delivery_date__c))) &amp; 
IF(AND(DAY(WOO_Requested_delivery_date__c)&gt;0,DAY(WOO_Requested_delivery_date__c)&lt;9),TEXT(0)&amp;TEXT(DAY(WOO_Requested_delivery_date__c)),TEXT(DAY(WOO_Requested_delivery_date__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Requested delivery date sap format</label>
    <type>Text</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_SAP_status__c.field-meta.xml
<CustomField>
    <fullName>WOO_SAP_status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Simulated OK</fullName>
            </value>
            <value>
                <fullName>Simulated with errors</fullName>
            </value>
            <value>
                <fullName>Ready to be sent</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>NotSent</fullName>
                <default>true</default>
                <label>Not Sent</label>
            </value>
            <value>
                <fullName>SentWithErrors</fullName>
                <label>Sent(Has Errors)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_WMF_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>WOO_WMF_Order_Number__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Number</label>
    <type>Text</type>
</CustomField>

force-app/wow/wmf_order/classes/WOO_SendOrderFileToAzureStorageTEST.cls
@IsTest
public with sharing class WOO_SendOrderFileToAzureStorageTEST {
    // Cannot use system.runAs() because of this error : System.CalloutException: You have uncommitted work pending. Please commit or rollback before calling out
    // API v.49
    @TestSetup
    static void setup() {
        Account acc = (Account) TestFactory.createSObjectAndInsert(
            new Account(
                LastName = 'toto',
                PersonMailingCity = 'Berlin',
                PersonMailingPostalCode = '12359',
                PersonMailingStreet = 'Johannisthaler Chaussee 169'
            )
        );
        acc = [SELECT Id, personContactId FROM Account WHERE LastName = 'toto'];
        Case c = (Case) TestFactory.createSObject(
            new Case(Case_Country__c = 'DE', AccountId = acc.Id, ContactId = acc.personContactId)
        );
        insert c;
        WOO_WMF_Orders__c order = new WOO_WMF_Orders__c(
            WOO_Order_Type__c = 'Finished products',
            WOO_Case__c = c.Id,
            WOO_Comment__c = 'Order comment',
            WOO_Requested_delivery_date__c = Date.newInstance(2050, 2, 17)
        );
        insert order;
        WOO_WMF_Order_Line_Item__c oli = new WOO_WMF_Order_Line_Item__c(
            WOO_WMF_Order__c = order.Id,
            WOO_Country__c = 'DE',
            WOO_Comment__c = 'Order line item comment'
        );
        insert oli;
    }

    @IsTest
    private static void sendFileToAzureSuccess() {
        WOO_WMF_Orders__c order = [
            SELECT Id, WOO_SAP_status__c
            FROM WOO_WMF_Orders__c
            WHERE WOO_Order_Type__c = 'Finished products'
        ];
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator('', 201));
        Test.startTest();
        order.WOO_SAP_status__c = 'Ready to be sent';
        update order;
        Test.stopTest();

        order = [
            SELECT Id, WOO_Is_File_Created__c
            FROM WOO_WMF_Orders__c
            WHERE WOO_Order_Type__c = 'Finished products'
        ];
        System.assertEquals(true, order.WOO_Is_File_Created__c, 'The file is not sent');
    }

    @IsTest
    private static void sendFileToAzureFail() {
        WOO_WMF_Orders__c order = [
            SELECT Id, WOO_SAP_status__c
            FROM WOO_WMF_Orders__c
            WHERE WOO_Order_Type__c = 'Finished products'
        ];
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator('', 500));
        Test.startTest();
        order.WOO_SAP_status__c = 'Ready to be sent';
        update order;
        Test.stopTest();

        order = [
            SELECT Id, WOO_Is_File_Created__c
            FROM WOO_WMF_Orders__c
            WHERE WOO_Order_Type__c = 'Finished products'
        ];
        System.assertEquals(false, order.WOO_Is_File_Created__c, 'The file is not sent');
    }

    @IsTest
    private static void checkFileStructure() {
        WOO_WMF_Orders__c order = [
            SELECT
                Id,
                WOO_WMF_Order_Number__c,
                WOO_Comment__c,
                WOO_Commercial_organization__c,
                WOO_CPD_client_code__c,
                WOO_Order_Type__c,
                WOO_Requested_delivery_date_sap_format__c
            FROM WOO_WMF_Orders__c
            LIMIT 1
        ];
        Case c = [
            SELECT caseNumber, Account.Title_2__c, Account.PersonEmail, Account.Name
            FROM Case
            LIMIT 1
        ];
        List<WOO_WMF_Order_Line_Item__c> oli = [
            SELECT
                WOO_Product_CMMF__c,
                WOO_Requested_quantity__c,
                WOO_Comment__c,
                WOO_WMF_Order__r.WOO_WMF_Order_Number__c
            FROM WOO_WMF_Order_Line_Item__c
        ];
        String body = WOO_AzureStorageServicesBlob.buildRequestBody(order, c, oli);
        System.assertEquals('AKO', body.left(3), 'first 3 header characters are wrong');
        System.assertEquals(4, body.countMatches('\r\n'), 'Number of lines incorrect');
        System.debug(body.length());
        System.assertEquals(
            'APO',
            body.substring(1450, 1453),
            'first 3 order characters are wrong'
        );
        System.assertEquals(
            'ATX',
            body.substring(1596, 1599),
            'first 3 header comment characters are wrong'
        );
        System.assertEquals(
            '0000  ',
            body.substring(1644, 1650),
            'POSNR field for header comment is wrong'
        );
        System.assertEquals(
            'ATX',
            body.substring(1722, 1725),
            'first 3 order comment characters are wrong'
        );
        System.assertEquals(
            '0001  ',
            body.substring(1770, 1776),
            'POSNR field for order comment is wrong'
        );
        System.assertEquals('\r\n', body.right(2), 'first 3 header characters are wrong');
    }
}