force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/WOO_WMF_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_Assigment__c.field-meta.xml
<CustomField>
    <fullName>WOO_Assigment__c</fullName>
    <label>Assigment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>004</fullName>
                <label>004 - SCHADEN (PERSONEN-UND/ODER SAC</label>
            </value>
            <value>
                <fullName>010</fullName>
                <label>010 - IG BERECHTIGT</label>
            </value>
            <value>
                <fullName>011</fullName>
                <label>011 - IG NICHT BERECHTIGT</label>
            </value>
            <value>
                <fullName>012</fullName>
                <label>012 - IG KULANZ</label>
            </value>
            <value>
                <fullName>020</fullName>
                <label>020 - AG KULANZ</label>
            </value>
            <value>
                <fullName>021</fullName>
                <label>021 - AG BESONDERHEITEN</label>
            </value>
            <value>
                <fullName>022</fullName>
                <label>022 - AG RÜCKSENDUNG</label>
            </value>
            <value>
                <fullName>999</fullName>
                <label>999 - NICHT RELEVANT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_Comment__c.field-meta.xml
<CustomField>
    <fullName>WOO_Comment__c</fullName>
    <label>Comment</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_Defect_Location__c.field-meta.xml
<CustomField>
    <fullName>WOO_Defect_Location__c</fullName>
    <label>Defect Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>001</fullName>
                <label>001 - ABDECKUNG</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>002 - ARM</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>003 - AUFHÄNGUNG</label>
            </value>
            <value>
                <fullName>005</fullName>
                <label>005 - AUSGUß</label>
            </value>
            <value>
                <fullName>008</fullName>
                <label>008 - BESCHICHTUNG</label>
            </value>
            <value>
                <fullName>009</fullName>
                <label>009 - BESPANNUNG</label>
            </value>
            <value>
                <fullName>012</fullName>
                <label>012 - ARTIKEL</label>
            </value>
            <value>
                <fullName>013</fullName>
                <label>013 - BODEN AUSSEN</label>
            </value>
            <value>
                <fullName>014</fullName>
                <label>014 - BODEN INNEN</label>
            </value>
            <value>
                <fullName>015</fullName>
                <label>015 - BOLZEN</label>
            </value>
            <value>
                <fullName>017</fullName>
                <label>017 - BÜGEL</label>
            </value>
            <value>
                <fullName>019</fullName>
                <label>019 - ETIKETT</label>
            </value>
            <value>
                <fullName>020</fullName>
                <label>020 - DECKEL/HAUBE</label>
            </value>
            <value>
                <fullName>021</fullName>
                <label>021 - DEKOR</label>
            </value>
            <value>
                <fullName>022</fullName>
                <label>022 - DICHTUNG</label>
            </value>
            <value>
                <fullName>026</fullName>
                <label>026 - ERSATZ</label>
            </value>
            <value>
                <fullName>029</fullName>
                <label>029 - GESTELL</label>
            </value>
            <value>
                <fullName>030</fullName>
                <label>030 - FEDER</label>
            </value>
            <value>
                <fullName>031</fullName>
                <label>031 - FUSS</label>
            </value>
            <value>
                <fullName>032</fullName>
                <label>032 - HALTERUNG/ANSCHLAG</label>
            </value>
            <value>
                <fullName>033</fullName>
                <label>033 - GEWINDE</label>
            </value>
            <value>
                <fullName>035</fullName>
                <label>035 - GRIFF/HEFT</label>
            </value>
            <value>
                <fullName>036</fullName>
                <label>036 - TOPFGRIFF</label>
            </value>
            <value>
                <fullName>037</fullName>
                <label>037 - DECKELGRIFF</label>
            </value>
            <value>
                <fullName>038</fullName>
                <label>038 - INDUKTIONSBODEN</label>
            </value>
            <value>
                <fullName>039</fullName>
                <label>039 - ALLHERDBODEN</label>
            </value>
            <value>
                <fullName>040</fullName>
                <label>040 - HOHE KANTE</label>
            </value>
            <value>
                <fullName>041</fullName>
                <label>041 - DECKELGRIFF SKT</label>
            </value>
            <value>
                <fullName>042</fullName>
                <label>042 - DECKEL SKT</label>
            </value>
            <value>
                <fullName>043</fullName>
                <label>043 - KANTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_Defect_type__c.field-meta.xml
<CustomField>
    <fullName>WOO_Defect_type__c</fullName>
    <label>Defect type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>001</fullName>
                <label>001 - ABBLASEN SCHLAGARTIG</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>002 - ANFRESSUNGEN</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>003 - ANGELAUFEN</label>
            </value>
            <value>
                <fullName>004</fullName>
                <label>004 - AUSGEBLEICHT</label>
            </value>
            <value>
                <fullName>005</fullName>
                <label>005 - AUSGEBROCHEN</label>
            </value>
            <value>
                <fullName>006</fullName>
                <label>006 - ANKLEBEN</label>
            </value>
            <value>
                <fullName>007</fullName>
                <label>007 - BOMBIERUNG</label>
            </value>
            <value>
                <fullName>008</fullName>
                <label>008 - ABGEBLÄTTERT/AUFGESTIEGEN</label>
            </value>
            <value>
                <fullName>009</fullName>
                <label>009 - BLASEN</label>
            </value>
            <value>
                <fullName>010</fullName>
                <label>010 - DELLEN/VERBEULT</label>
            </value>
            <value>
                <fullName>011</fullName>
                <label>011 - SCHLAGMARKEN</label>
            </value>
            <value>
                <fullName>012</fullName>
                <label>012 - DRUCKSTELLEN</label>
            </value>
            <value>
                <fullName>013</fullName>
                <label>013 - DURCHGEDRÜCKT</label>
            </value>
            <value>
                <fullName>014</fullName>
                <label>014 - NIETABPLATZER</label>
            </value>
            <value>
                <fullName>015</fullName>
                <label>015 - STÖRGERÄUSCHE</label>
            </value>
            <value>
                <fullName>016</fullName>
                <label>016 - EINFALLSTELLEN</label>
            </value>
            <value>
                <fullName>017</fullName>
                <label>017 - ZERSPRUNGEN</label>
            </value>
            <value>
                <fullName>018</fullName>
                <label>018 - FUNKTION SKT</label>
            </value>
            <value>
                <fullName>019</fullName>
                <label>019 - FALSCH/VERTAUSCHT</label>
            </value>
            <value>
                <fullName>020</fullName>
                <label>020 - MONTAGEFEHLER</label>
            </value>
            <value>
                <fullName>021</fullName>
                <label>021 - FARBABWEICHUNG</label>
            </value>
            <value>
                <fullName>022</fullName>
                <label>022 - INDUKTIONSPROBLEME</label>
            </value>
            <value>
                <fullName>023</fullName>
                <label>023 - DRUCKWERTE</label>
            </value>
            <value>
                <fullName>024</fullName>
                <label>024 - FEHLT/UNVOLLSTÄNDIG</label>
            </value>
            <value>
                <fullName>025</fullName>
                <label>025 - FLECKIG</label>
            </value>
            <value>
                <fullName>026</fullName>
                <label>026 - STUMPF</label>
            </value>
            <value>
                <fullName>027</fullName>
                <label>027 - FORMABWEICHUNG</label>
            </value>
            <value>
                <fullName>028</fullName>
                <label>028 - NICHT MEHR VERWENDEN</label>
            </value>
            <value>
                <fullName>029</fullName>
                <label>029 - GRATIG/SCHARFKANTIG/RAUH</label>
            </value>
            <value>
                <fullName>030</fullName>
                <label>030 - ABGEBROCHEN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_Product_CMMF__c.field-meta.xml
<CustomField>
    <fullName>WOO_Product_CMMF__c</fullName>
    <formula>WOO_Product__r.CMMF__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product CMMF</label>
    <type>Text</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_Repair_instructions__c.field-meta.xml
<CustomField>
    <fullName>WOO_Repair_instructions__c</fullName>
    <label>Repair instructions</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>01 - Wellenschliff  T/H</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>02 - Schärfen Küchenmesser  T/H</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>03 - Microcut  T/H</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>05 - Klinge ersetzen  T/H</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>06 - Montagerep. SKT  T/H</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>07 - Sonstige Rep / Liebhaberstück</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>14 - Schärfen Fremdware</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>27 - Aufarb. Sonstiges T/H</label>
            </value>
            <value>
                <fullName>52</fullName>
                <label>52 - Umtausch  T/H</label>
            </value>
            <value>
                <fullName>53</fullName>
                <label>53 - Zurück  T/H</label>
            </value>
            <value>
                <fullName>54</fullName>
                <label>54 - Lasergravur  T/H</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>60 - Montagerep. Griff  T/H</label>
            </value>
            <value>
                <fullName>61</fullName>
                <label>61 - Montagerep. gemischt</label>
            </value>
            <value>
                <fullName>62</fullName>
                <label>62 - Glattschliff  T/H</label>
            </value>
            <value>
                <fullName>70</fullName>
                <label>70 - Aufarb. Topf T/H</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_Requested_quantity__c.field-meta.xml
<CustomField>
    <fullName>WOO_Requested_quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Requested quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_WMF_Order__c.field-meta.xml
<CustomField>
    <fullName>WOO_WMF_Order__c</fullName>
    <label>CCC Order</label>
    <referenceTo>WOO_WMF_Orders__c</referenceTo>
    <relationshipName>WMF_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/WOO_WMF_Orders__c.object-meta.xml
<CustomObject>
    <description>Object for the orders</description>
    <label>CCC order</label>
    <pluralLabel>CCC orders</pluralLabel>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Case__c.field-meta.xml
<CustomField>
    <fullName>WOO_Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>CCC orders</relationshipLabel>
    <relationshipName>WMF_Order</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Is_File_Created__c.field-meta.xml
<CustomField>
    <fullName>WOO_Is_File_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to check if the file has been created in azure storage</description>
    <label>Is File Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_WMF_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>WOO_WMF_Order_Number__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Number</label>
    <type>Text</type>
</CustomField>

force-app/wow/wmf_order/classes/WOO_SendOrderFileToAzureStorage.cls
public with sharing class WOO_SendOrderFileToAzureStorage implements Queueable, Database.AllowsCallouts {
    private List<WOO_WMF_Orders__c> newOrders { get; set; }

    public WOO_SendOrderFileToAzureStorage(List<WOO_WMF_Orders__c> newOrders) {
        this.newOrders = newOrders;
    }

    public void execute(QueueableContext context) {
        WOO_WMF_Orders__c order = newOrders[0];
        Case caseOrder = [
            SELECT
                Id,
                Casenumber,
                Account.Title_2__c,
                Account.Name,
                Account.PersonMailingPostalCode,
                Account.PersonMailingCity,
                Account.PersonMailingStreet,
                Account.PersonEmail,
                Account.Salutation
            FROM Case
            WHERE Id = :order.WOO_Case__c
        ];
        List<WOO_WMF_Order_Line_Item__c> orderLineItems = [
            SELECT
                Id,
                WOO_Product_CMMF__c,
                WOO_Requested_quantity__c,
                WOO_Comment__c,
                WOO_WMF_Order__r.WOO_WMF_Order_Number__c,
                WOO_Repair_instructions__c,
                WOO_Assigment__c,
                WOO_Defect_Location__c,
                WOO_Defect_type__c
            FROM WOO_WMF_Order_Line_Item__c
            WHERE WOO_WMF_Order__c = :order.Id
        ];
        HttpResponse response = WOO_AzureStorageServicesBlob.putFileInAzureStorageServicesBlob(
            order,
            caseOrder,
            orderLineItems
        );
        if (response.getStatusCode() == 201) {
            order.WOO_Is_File_Created__c = true;
            update order;
        } else {
            System.debug('An error occured :( ' + response.getStatusCode());
        }
    }

    public static List<WOO_WMF_Orders__c> getOrdersWithFileToSendToAzure(
        List<WOO_WMF_Orders__c> orders,
        Map<Id, WOO_WMF_Orders__c> oldMap
    ) {
        List<WOO_WMF_Orders__c> ordersWithFileToSendToAzure = new List<WOO_WMF_Orders__c>();
        for (WOO_WMF_Orders__c order : orders) {
            if (
                orders.size() == 1 &&
                order.WOO_SAP_status__c == 'Ready to be sent' &&
                order.WOO_SAP_status__c != oldMap.get(order.Id).WOO_SAP_status__c
            ) {
                ordersWithFileToSendToAzure.add(order);
            }
        }
        return ordersWithFileToSendToAzure;
    }
}