force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/WOO_WMF_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_Comment__c.field-meta.xml
<CustomField>
    <fullName>WOO_Comment__c</fullName>
    <label>Comment</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_Country__c.field-meta.xml
<CustomField>
    <fullName>WOO_Country__c</fullName>
    <defaultValue>IF($User.UserCountryCode__c = &apos;WM&apos;, &apos;DE&apos;, $User.UserCountryCode__c)</defaultValue>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_Product_CMMF__c.field-meta.xml
<CustomField>
    <fullName>WOO_Product_CMMF__c</fullName>
    <formula>WOO_Product__r.CMMF__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product CMMF</label>
    <type>Text</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_Requested_quantity__c.field-meta.xml
<CustomField>
    <fullName>WOO_Requested_quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Requested quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_WMF_Order__c.field-meta.xml
<CustomField>
    <fullName>WOO_WMF_Order__c</fullName>
    <label>CCC Order</label>
    <referenceTo>WOO_WMF_Orders__c</referenceTo>
    <relationshipName>WMF_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/WOO_WMF_Orders__c.object-meta.xml
<CustomObject>
    <description>Object for the orders</description>
    <label>CCC order</label>
    <pluralLabel>CCC orders</pluralLabel>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Case__c.field-meta.xml
<CustomField>
    <fullName>WOO_Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>CCC orders</relationshipLabel>
    <relationshipName>WMF_Order</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_CPD_client_code__c.field-meta.xml
<CustomField>
    <fullName>WOO_CPD_client_code__c</fullName>
    <label>CPD client code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>WOO_Commercial_organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>98001019</fullName>
                <default>true</default>
                <label>CKW End user Germany K101</label>
            </value>
            <value>
                <fullName>98001020</fullName>
                <label>CKW End user Austria K101</label>
            </value>
            <value>
                <fullName>98001103</fullName>
                <label>SDA End user Germany K101</label>
            </value>
            <value>
                <fullName>98001120</fullName>
                <label>SDA End user Austria K101</label>
            </value>
            <value>
                <fullName>98001102</fullName>
                <label>SDA Traders Germany K101</label>
            </value>
            <value>
                <fullName>98001030</fullName>
                <label>CKW End user inside Europe K109</label>
            </value>
            <value>
                <fullName>98001111</fullName>
                <label>SDA End user inside Europe K109</label>
            </value>
            <value>
                <fullName>98001113</fullName>
                <label>SDA Traders inside Europe K109</label>
            </value>
            <value>
                <fullName>98001021</fullName>
                <isActive>false</isActive>
                <label>98001021</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>WOO_Order_Type__c</fullName>
    <defaultValue>&apos;Finished products&apos;</defaultValue>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finished products</fullName>
            </value>
            <value>
                <fullName>Spare part</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
                <label>Spare part and accessories (Free Of Charge)</label>
            </value>
            <value>
                <fullName>FEX</fullName>
                <label>Finish product (Free Exchange)</label>
            </value>
            <value>
                <fullName>Goodwill</fullName>
                <label>Other free order type (goodwill)</label>
            </value>
            <value>
                <fullName>Goodwill_SpareParts</fullName>
                <label>Other free order type (goodwill : Spare Parts)</label>
            </value>
            <value>
                <fullName>Goodwill_Product</fullName>
                <label>Other free order type (goodwill : Product)</label>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Requested_delivery_date__c.field-meta.xml
<CustomField>
    <fullName>WOO_Requested_delivery_date__c</fullName>
    <label>Requested delivery date</label>
    <type>Date</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_WMF_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>WOO_WMF_Order_Number__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Number</label>
    <type>Text</type>
</CustomField>

force-app/wow/wmf_order/classes/WOO_OrderCreateWrapperTEST.cls
@IsTest
public with sharing class WOO_OrderCreateWrapperTEST {
    public static User setupUser;
    static {
        setupUser = (User) TestFactory.createSObject(new user(), TestFactoryUser.UserSetup.class);
    }

    @TestSetup
    static void setup() {
        System.runAs(setupUser) {
            Account acc = (Account) TestFactory.createSObject(
                new Account(
                    LastName = 'toto',
                    PersonMailingCity = 'Berlin',
                    PersonMailingPostalCode = '12359',
                    PersonMailingStreet = 'Johannisthaler Chaussee 169'
                )
            );
            insert acc;
            acc = [SELECT Id, personContactId FROM Account WHERE LastName = 'toto'];
            Case c = (Case) TestFactory.createSObject(
                new Case(
                    Case_Country__c = 'DE',
                    AccountId = acc.Id,
                    ContactId = acc.personContactId
                )
            );
            insert c;
            WOO_WMF_Orders__c order = new WOO_WMF_Orders__c(
                WOO_Order_Type__c = 'Finished products',
                WOO_Case__c = c.Id,
                WOO_Requested_delivery_date__c = Date.newInstance(2050, 2, 17)
            );
            insert order;
            WOO_WMF_Order_Line_Item__c oli = new WOO_WMF_Order_Line_Item__c(
                WOO_WMF_Order__c = order.Id,
                WOO_Country__c = 'DE'
            );
            insert oli;
        }
    }

    @IsTest
    private static void orderWrapperHeader() {
        WOO_OrderCreateWrapper.header h = new WOO_OrderCreateWrapper.header();
        System.assertEquals(53, h.mapSAPfieldSize.size(), 'The number of fields is incorrect');
        List<integer> i = h.mapSAPfieldSize.values();
        Integer sum = 0;
        for (integer j : i) {
            sum = sum + j;
        }
        System.assertEquals(1448, sum, 'The number of characters is incorrect');
    }

    @IsTest
    private static void checkFieldValueNotAboveMaxLength() {
        String result = WOO_OrderCreateWrapper.formatFieldValue('blabla', 10); // 'VBELN'
        System.assert(
            result.contains('    '),
            'The field does not have the correct number of spaces'
        );
        System.assertEquals(10, result.length(), 'The length is incorrect');
    }

    @IsTest
    private static void checkFieldValueAboveMaxLength() {
        new WOO_OrderCreateWrapper.header();
        String result = WOO_OrderCreateWrapper.formatFieldValue('blablablabla', 10); // 'VBELN'
        System.assertEquals(10, result.trim().length(), 'The length is incorrect');
    }

    @IsTest
    private static void checkFirst2FieldsInHeaderLine() {
        WOO_OrderCreateWrapper.header h = new WOO_OrderCreateWrapper.header();
        h.fillHeaderWithFixedValues(new WOO_WMF_Orders__c(WOO_Order_Type__c = 'Finished products'));
        System.assertEquals(
            'AKOK1TA',
            h.headerLine.left(7),
            'The first characters 7 are incorrect for finished products type'
        );
        h = new WOO_OrderCreateWrapper.header();
        h.fillHeaderWithFixedValues(new WOO_WMF_Orders__c(WOO_Order_Type__c = 'Spare part'));
        System.assertEquals(
            'AKOK1TS',
            h.headerLine.left(7),
            'The first 7 characters are incorrect for spare parts type'
        );
    }

    @IsTest
    private static void checkHeaderFieldIsAtTheCorrectPosition() {
        WOO_OrderCreateWrapper.header h = new WOO_OrderCreateWrapper.header();
        WOO_WMF_Orders__c order = new WOO_WMF_Orders__c(
            WOO_Order_Type__c = 'Finished products',
            WOO_CPD_client_code__c = '98001021'
        );
        Case c = [
            SELECT id, caseNumber, Account.Title_2__c, Account.PersonEmail, Account.Name
            FROM Case
            WHERE Case_Country__c = 'DE'
        ];
        h.fillHeader(c, order);
        System.assertEquals(
            '98001021  ',
            h.headerLine.substring(31, 41),
            'The field is not correctly inserted'
        );
    }

    @IsTest
    private static void orderWrapperOrderLine() {
        WOO_OrderCreateWrapper.OrderLine ol = new WOO_OrderCreateWrapper.OrderLine();
        System.assertEquals(15, ol.mapSAPfieldSize.size(), 'The number of fields is incorrect');
        List<integer> i = ol.mapSAPfieldSize.values();
        Integer sum = 0;
        for (integer j : i) {
            sum = sum + j;
        }
        System.assertEquals(144, sum, 'The number of characters is incorrect');
    }

    @IsTest
    private static void checkOrderLineItemFieldIsAtTheCorrectPosition() {
        WOO_OrderCreateWrapper.OrderLine ol = new WOO_OrderCreateWrapper.OrderLine();
        WOO_WMF_Order_Line_Item__c oli = [
            SELECT
                Id,
                WOO_Product_CMMF__c,
                WOO_Requested_quantity__c,
                WOO_WMF_Order__r.WOO_WMF_Order_Number__c
            FROM WOO_WMF_Order_Line_Item__c
            LIMIT 1
        ];
        ol.fillOrderLine(oli);
        System.assert(ol.orderLine.left(3) == 'APO', 'The first 3 characters are wrong');
        System.assertEquals(
            oli.WOO_Requested_quantity__c + '             ',
            ol.orderLine.substring(66, 80),
            'The field is not correctly inserted'
        );
    }

    @IsTest
    private static void orderWrapperHeaderText() {
        WOO_OrderCreateWrapper.HeaderText ht = new WOO_OrderCreateWrapper.HeaderText();
        System.assertEquals(5, ht.mapSAPfieldSize.size(), 'The number of fields is incorrect');
        List<integer> i = ht.mapSAPfieldSize.values();
        Integer sum = 0;
        for (integer j : i) {
            sum = sum + j;
        }
        System.assertEquals(124, sum, 'The number of characters is incorrect');
    }

    @IsTest
    private static void checkHeaderTextFieldIsAtTheCorrectPosition() {
        WOO_OrderCreateWrapper.HeaderText ht = new WOO_OrderCreateWrapper.HeaderText();
        WOO_WMF_Orders__c order = [
            SELECT Id, WOO_WMF_Order_Number__c
            FROM WOO_WMF_Orders__c
            LIMIT 1
        ];
        ht.fillHeaderText(order);
        System.assert(ht.headerText.left(3) == 'ATX', 'The first 3 characters are wrong');
        System.assertEquals(
            order.WOO_WMF_Order_Number__c + '    ',
            ht.headerText.substring(3, 13),
            'The field is not correctly inserted'
        );
    }

    @IsTest
    private static void orderWrapperOrderText() {
        WOO_OrderCreateWrapper.OrderText ot = new WOO_OrderCreateWrapper.OrderText();
        System.assertEquals(5, ot.mapSAPfieldSize.size(), 'The number of fields is incorrect');
        List<integer> i = ot.mapSAPfieldSize.values();
        Integer sum = 0;
        for (integer j : i) {
            sum = sum + j;
        }
        System.assertEquals(124, sum, 'The number of characters is incorrect');
    }

    @IsTest
    private static void checkOrderTextFieldIsAtTheCorrectPosition() {
        WOO_OrderCreateWrapper.OrderText ht = new WOO_OrderCreateWrapper.OrderText();
        WOO_WMF_Order_Line_Item__c oli = [
            SELECT id, WOO_Comment__c, WOO_WMF_Order__r.WOO_WMF_Order_Number__c
            FROM WOO_WMF_Order_Line_Item__c
            LIMIT 1
        ];
        ht.fillOrderText(oli);
        System.assert(ht.OrderText.left(3) == 'ATX', 'The first 3 characters are wrong');
        System.assertEquals(
            oli.WOO_WMF_Order__r.WOO_WMF_Order_Number__c + '    ',
            ht.OrderText.substring(3, 13),
            'The field is not correctly inserted'
        );
    }
}