force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/WOO_WMF_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_Comment__c.field-meta.xml
<CustomField>
    <fullName>WOO_Comment__c</fullName>
    <label>Comment</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_Product__c.field-meta.xml
<CustomField>
    <fullName>WOO_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.Country__c</field>
            <operation>equals</operation>
            <valueField>$Source.WOO_Country__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipName>WMF_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_Requested_quantity__c.field-meta.xml
<CustomField>
    <fullName>WOO_Requested_quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Requested quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_WMF_Order__c.field-meta.xml
<CustomField>
    <fullName>WOO_WMF_Order__c</fullName>
    <label>CCC Order</label>
    <referenceTo>WOO_WMF_Orders__c</referenceTo>
    <relationshipName>WMF_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/WOO_WMF_Orders__c.object-meta.xml
<CustomObject>
    <description>Object for the orders</description>
    <label>CCC order</label>
    <pluralLabel>CCC orders</pluralLabel>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Account__c.field-meta.xml
<CustomField>
    <fullName>WOO_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>WMF Order</relationshipLabel>
    <relationshipName>WMF_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Account_City__c.field-meta.xml
<CustomField>
    <fullName>WOO_Account_City__c</fullName>
    <label>Account City</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Account_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>WOO_Account_Postal_Code__c</fullName>
    <label>Account Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Account_Street__c.field-meta.xml
<CustomField>
    <fullName>WOO_Account_Street__c</fullName>
    <label>Account Street</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Case__c.field-meta.xml
<CustomField>
    <fullName>WOO_Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>CCC orders</relationshipLabel>
    <relationshipName>WMF_Order</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_External_Id__c.field-meta.xml
<CustomField>
    <fullName>WOO_External_Id__c</fullName>
    <description>For unit tests</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>55</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Product__c.field-meta.xml
<CustomField>
    <fullName>WOO_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used for RecordType FreeOrders</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.Country__c</field>
            <operation>equals</operation>
            <valueField>$Source.Product_Country__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Requested_delivery_date__c.field-meta.xml
<CustomField>
    <fullName>WOO_Requested_delivery_date__c</fullName>
    <label>Requested delivery date</label>
    <type>Date</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_SAP_status__c.field-meta.xml
<CustomField>
    <fullName>WOO_SAP_status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Simulated OK</fullName>
            </value>
            <value>
                <fullName>Simulated with errors</fullName>
            </value>
            <value>
                <fullName>Ready to be sent</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>NotSent</fullName>
                <default>true</default>
                <label>Not Sent</label>
            </value>
            <value>
                <fullName>SentWithErrors</fullName>
                <label>Sent(Has Errors)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/wow/wmf_order/classes/OrderFlow_TEST.cls
@isTest
public with sharing class OrderFlow_TEST {
    @TestSetup
    static void setup() {
        User agentUser = (User) TestFactory.createSObjectAndInsert(
            new User(Username = 'AgentWMF@AgentWMF.com'),
            TestFactoryUser.CCCBackAgent.class
        );
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'WOO_WMF_Order'];
        PermissionSetAssignment psa = new PermissionSetAssignment(
            AssigneeId = agentUser.Id,
            PermissionSetId = ps.id
        );
        insert psa;
        System.runAs(agentUser) {
            Id finishedProductRecordType = [
                SELECT Id
                FROM RecordType
                WHERE sObjectType = 'Product2' AND Name = 'Produit fini'
                LIMIT 1
            ]
            .Id;
            Account acc = (Account) TestFactory.createSObjectAndInsert(
                new Account(
                    PersonMailingCity = 'Berlin',
                    PersonMailingPostalCode = '12359',
                    PersonMailingStreet = 'Johannisthaler Chaussee 169'
                ),
                TestFactoryAccount.WOWConsumer.class
            );
            acc = [SELECT PersonContactId FROM Account WHERE Id = :acc.Id];
            Case c = (Case) TestFactory.createSObjectAndInsert(
                new Case(ContactId = acc.PersonContactId)
            );
            Product2 p = (Product2) TestFactory.createSObjectAndInsert(
                new Product2(CMMF__c = 'P1', RecordTypeId = finishedProductRecordType)
            );
            WOO_WMF_Orders__c order = (WOO_WMF_Orders__c) TestFactory.createSObjectAndInsert(
                new WOO_WMF_Orders__c(WOO_Case__c = c.Id, WOO_External_Id__c = 'testOrder')
            );
            TestFactory.createSObjectAndInsert(
                new WOO_WMF_Order_Line_Item__c(
                    WOO_WMF_Order__c = order.id,
                    WOO_Product__c = p.Id,
                    WOO_Requested_quantity__c = 1
                )
            );
        }
    }

    @isTest
    private static void ordersUpdatePreventedWhenOrderSentTest() {
        User agentUser = [SELECT Id FROM User WHERE Username = 'AgentWMF@AgentWMF.com'];
        Boolean orderUpdatePrevented = false;
        Boolean orderLineItemUpdatePrevented = false;
        System.runAs(agentUser) {
            WOO_WMF_Orders__c order = [SELECT Id FROM WOO_WMF_Orders__c];
            WOO_WMF_Order_Line_Item__c oli = [SELECT Id FROM WOO_WMF_Order_Line_Item__c];
            order.WOO_SAP_status__c = 'Sent';
            update order;

            Test.startTest();
            try {
                order.WOO_Comment__c = 'test';
                update order;
            } catch (Exception e) {
                orderUpdatePrevented = true;
            }

            try {
                oli.WOO_Comment__c = 'test';
                update oli;
            } catch (Exception e) {
                orderLineItemUpdatePrevented = true;
            }
            Test.stopTest();

            System.assertEquals(
                orderUpdatePrevented,
                true,
                'Order delete should be prevented when order is already sent'
            );
            System.assertEquals(
                orderLineItemUpdatePrevented,
                true,
                'Order line item delete should be prevented when order is already sent'
            );
        }
    }

    @isTest
    private static void ordersDeletePreventedWhenOrderSentTest() {
        User agentUser = [SELECT Id FROM User WHERE Username = 'AgentWMF@AgentWMF.com'];
        Boolean orderDeletePrevented = false;
        Boolean orderLineItemDeletePrevented = false;
        System.runAs(agentUser) {
            WOO_WMF_Orders__c order = [SELECT Id FROM WOO_WMF_Orders__c];
            WOO_WMF_Order_Line_Item__c oli = [SELECT Id FROM WOO_WMF_Order_Line_Item__c];
            order.WOO_SAP_status__c = 'Sent';
            update order;

            Test.startTest();
            try {
                delete order;
            } catch (Exception e) {
                orderDeletePrevented = true;
            }

            try {
                delete oli;
            } catch (Exception e) {
                orderLineItemDeletePrevented = true;
            }
            Test.stopTest();

            System.assertEquals(
                orderDeletePrevented,
                true,
                'Order delete should be prevented when order is already sent'
            );
            System.assertEquals(
                orderLineItemDeletePrevented,
                true,
                'Order line item delete should be prevented when order is already sent'
            );
        }
    }

    @isTest
    private static void orderStatusResetWhenOrderLineItemDeletedTest() {
        User agentUser = [SELECT Id FROM User WHERE Username = 'AgentWMF@AgentWMF.com'];
        System.runAs(agentUser) {
            WOO_WMF_Orders__c order = [SELECT Id FROM WOO_WMF_Orders__c];
            WOO_WMF_Order_Line_Item__c oli = [SELECT Id FROM WOO_WMF_Order_Line_Item__c];
            order.WOO_SAP_status__c = 'Simulated with errors';
            update order;

            Test.startTest();
            delete oli;
            Test.stopTest();

            order = [SELECT WOO_SAP_status__c FROM WOO_WMF_Orders__c];
            System.assertEquals(
                order.WOO_SAP_status__c,
                'Draft',
                'Order which status is Simulated Ok should be reset if an orderLineItem is deleted'
            );
        }
    }

    @isTest
    private static void orderStatusResetWhenSentOrderUpdatedTest() {
        User agentUser = [SELECT Id FROM User WHERE Username = 'AgentWMF@AgentWMF.com'];
        System.runAs(agentUser) {
            WOO_WMF_Orders__c order = [SELECT Id FROM WOO_WMF_Orders__c];
            order.WOO_SAP_status__c = 'Simulated with errors';
            update order;

            Test.startTest();
            DateTime dT = System.now();
            order.WOO_Requested_delivery_date__c = date.newinstance(
                dT.year(),
                dT.month(),
                dT.day()
            );
            update order;
            Test.stopTest();

            order = [SELECT WOO_SAP_status__c FROM WOO_WMF_Orders__c];
            System.assertEquals(
                order.WOO_SAP_status__c,
                'Draft',
                'Order which status is Simulated Ok should be reset if an orderLineItem is deleted'
            );
        }
    }

    @isTest
    private static void orderAccountFieldFilledWhenSimulatedOkTest() {
        User agentUser = [SELECT Id FROM User WHERE Username = 'AgentWMF@AgentWMF.com'];
        System.runAs(agentUser) {
            WOO_WMF_Orders__c order = [SELECT Id FROM WOO_WMF_Orders__c];

            Test.startTest();
            order.WOO_SAP_status__c = 'Simulated OK';
            update order;
            Test.stopTest();

            order = [
                SELECT
                    WOO_Account__c,
                    WOO_Account_City__c,
                    WOO_Account_Postal_Code__c,
                    WOO_Account_Street__c
                FROM WOO_WMF_Orders__c
            ];
            System.assertEquals(
                String.isEmpty(order.WOO_Account__c),
                false,
                'Account should be retrieved when Status get to Simulated Ok'
            );
            System.assertEquals(
                String.isEmpty(order.WOO_Account_City__c),
                false,
                'Account City should be retrieved when Status get to Simulated Ok'
            );
            System.assertEquals(
                String.isEmpty(order.WOO_Account_Postal_Code__c),
                false,
                'Account Postal code should be retrieved when Status get to Simulated Ok'
            );
            System.assertEquals(
                String.isEmpty(order.WOO_Account_Street__c),
                false,
                'Account Street should be retrieved when Status get to Simulated Ok'
            );
        }
    }

    @isTest
    private static void orderAccountFieldGenerateErrorWhenEmpty() {
        User agentUser = [SELECT Id FROM User WHERE Username = 'AgentWMF@AgentWMF.com'];
        System.runAs(agentUser) {
            Account acc = [SELECT Id FROM Account LIMIT 1];
            Case c = [SELECT Id, AccountId FROM Case LIMIT 1];
            acc.PersonMailingCity = null;
            update acc;
            WOO_WMF_Orders__c order = (WOO_WMF_Orders__c) TestFactory.createSObject(
                new WOO_WMF_Orders__c(WOO_Case__c = c.Id)
            );
            Boolean orderError = false;
            Test.startTest();
            try {
                insert order;
            } catch (Exception e) {
                orderError = true;
            }
            Test.stopTest();
            System.assertEquals(
                true,
                orderError,
                'An error should be generated when trying to insert an order whith a case which account have no primary address'
            );
        }
    }
}