force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/WOO_WMF_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_Assigment__c.field-meta.xml
<CustomField>
    <fullName>WOO_Assigment__c</fullName>
    <label>Assigment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>004</fullName>
                <label>004 - SCHADEN (PERSONEN-UND/ODER SAC</label>
            </value>
            <value>
                <fullName>010</fullName>
                <label>010 - IG BERECHTIGT</label>
            </value>
            <value>
                <fullName>011</fullName>
                <label>011 - IG NICHT BERECHTIGT</label>
            </value>
            <value>
                <fullName>012</fullName>
                <label>012 - IG KULANZ</label>
            </value>
            <value>
                <fullName>020</fullName>
                <label>020 - AG KULANZ</label>
            </value>
            <value>
                <fullName>021</fullName>
                <label>021 - AG BESONDERHEITEN</label>
            </value>
            <value>
                <fullName>022</fullName>
                <label>022 - AG RÜCKSENDUNG</label>
            </value>
            <value>
                <fullName>999</fullName>
                <label>999 - NICHT RELEVANT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_Defect_Location__c.field-meta.xml
<CustomField>
    <fullName>WOO_Defect_Location__c</fullName>
    <label>Defect Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>001</fullName>
                <label>001 - ABDECKUNG</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>002 - ARM</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>003 - AUFHÄNGUNG</label>
            </value>
            <value>
                <fullName>005</fullName>
                <label>005 - AUSGUß</label>
            </value>
            <value>
                <fullName>008</fullName>
                <label>008 - BESCHICHTUNG</label>
            </value>
            <value>
                <fullName>009</fullName>
                <label>009 - BESPANNUNG</label>
            </value>
            <value>
                <fullName>012</fullName>
                <label>012 - ARTIKEL</label>
            </value>
            <value>
                <fullName>013</fullName>
                <label>013 - BODEN AUSSEN</label>
            </value>
            <value>
                <fullName>014</fullName>
                <label>014 - BODEN INNEN</label>
            </value>
            <value>
                <fullName>015</fullName>
                <label>015 - BOLZEN</label>
            </value>
            <value>
                <fullName>017</fullName>
                <label>017 - BÜGEL</label>
            </value>
            <value>
                <fullName>019</fullName>
                <label>019 - ETIKETT</label>
            </value>
            <value>
                <fullName>020</fullName>
                <label>020 - DECKEL/HAUBE</label>
            </value>
            <value>
                <fullName>021</fullName>
                <label>021 - DEKOR</label>
            </value>
            <value>
                <fullName>022</fullName>
                <label>022 - DICHTUNG</label>
            </value>
            <value>
                <fullName>026</fullName>
                <label>026 - ERSATZ</label>
            </value>
            <value>
                <fullName>029</fullName>
                <label>029 - GESTELL</label>
            </value>
            <value>
                <fullName>030</fullName>
                <label>030 - FEDER</label>
            </value>
            <value>
                <fullName>031</fullName>
                <label>031 - FUSS</label>
            </value>
            <value>
                <fullName>032</fullName>
                <label>032 - HALTERUNG/ANSCHLAG</label>
            </value>
            <value>
                <fullName>033</fullName>
                <label>033 - GEWINDE</label>
            </value>
            <value>
                <fullName>035</fullName>
                <label>035 - GRIFF/HEFT</label>
            </value>
            <value>
                <fullName>036</fullName>
                <label>036 - TOPFGRIFF</label>
            </value>
            <value>
                <fullName>037</fullName>
                <label>037 - DECKELGRIFF</label>
            </value>
            <value>
                <fullName>038</fullName>
                <label>038 - INDUKTIONSBODEN</label>
            </value>
            <value>
                <fullName>039</fullName>
                <label>039 - ALLHERDBODEN</label>
            </value>
            <value>
                <fullName>040</fullName>
                <label>040 - HOHE KANTE</label>
            </value>
            <value>
                <fullName>041</fullName>
                <label>041 - DECKELGRIFF SKT</label>
            </value>
            <value>
                <fullName>042</fullName>
                <label>042 - DECKEL SKT</label>
            </value>
            <value>
                <fullName>043</fullName>
                <label>043 - KANTE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_Product_CMMF__c.field-meta.xml
<CustomField>
    <fullName>WOO_Product_CMMF__c</fullName>
    <formula>WOO_Product__r.CMMF__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product CMMF</label>
    <type>Text</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/fields/WOO_Requested_quantity__c.field-meta.xml
<CustomField>
    <fullName>WOO_Requested_quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Requested quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Order_Line_Item__c/recordTypes/Repair.recordType-meta.xml
<RecordType>
    <fullName>Repair</fullName>
    <active>true</active>
    <description>Record Type for Repair order</description>
    <label>Repair</label>
</RecordType>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/WOO_WMF_Orders__c.object-meta.xml
<CustomObject>
    <description>Object for the orders</description>
    <label>CCC order</label>
    <pluralLabel>CCC orders</pluralLabel>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Account_City__c.field-meta.xml
<CustomField>
    <fullName>WOO_Account_City__c</fullName>
    <label>Account City</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Account_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>WOO_Account_Postal_Code__c</fullName>
    <label>Account Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Account_Street__c.field-meta.xml
<CustomField>
    <fullName>WOO_Account_Street__c</fullName>
    <label>Account Street</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Commercial_organization__c.field-meta.xml
<CustomField>
    <fullName>WOO_Commercial_organization__c</fullName>
    <label>Commercial organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>K101</fullName>
                <default>true</default>
                <label>K101</label>
            </value>
            <value>
                <fullName>K109</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_CPD_client_code__c.field-meta.xml
<CustomField>
    <fullName>WOO_CPD_client_code__c</fullName>
    <label>CPD client code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>WOO_Commercial_organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>98001019</fullName>
                <default>true</default>
                <label>CKW End user Germany K101</label>
            </value>
            <value>
                <fullName>98001020</fullName>
                <label>CKW End user Austria K101</label>
            </value>
            <value>
                <fullName>98001103</fullName>
                <label>SDA End user Germany K101</label>
            </value>
            <value>
                <fullName>98001120</fullName>
                <label>SDA End user Austria K101</label>
            </value>
            <value>
                <fullName>98001102</fullName>
                <label>SDA Traders Germany K101</label>
            </value>
            <value>
                <fullName>98001030</fullName>
                <label>CKW End user inside Europe K109</label>
            </value>
            <value>
                <fullName>98001111</fullName>
                <label>SDA End user inside Europe K109</label>
            </value>
            <value>
                <fullName>98001113</fullName>
                <label>SDA Traders inside Europe K109</label>
            </value>
            <value>
                <fullName>98001021</fullName>
                <isActive>false</isActive>
                <label>98001021</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>WOO_Order_Type__c</fullName>
    <defaultValue>&apos;Finished products&apos;</defaultValue>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finished products</fullName>
            </value>
            <value>
                <fullName>Spare part</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
                <label>Spare part and accessories (Free Of Charge)</label>
            </value>
            <value>
                <fullName>FEX</fullName>
                <label>Finish product (Free Exchange)</label>
            </value>
            <value>
                <fullName>Goodwill</fullName>
                <label>Other free order type (goodwill)</label>
            </value>
            <value>
                <fullName>Goodwill_SpareParts</fullName>
                <label>Other free order type (goodwill : Spare Parts)</label>
            </value>
            <value>
                <fullName>Goodwill_Product</fullName>
                <label>Other free order type (goodwill : Product)</label>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Requested_delivery_date_sap_format__c.field-meta.xml
<CustomField>
    <fullName>WOO_Requested_delivery_date_sap_format__c</fullName>
    <formula>TEXT(YEAR(WOO_Requested_delivery_date__c)) &amp; 
IF(AND(MONTH(WOO_Requested_delivery_date__c)&gt;0,MONTH(WOO_Requested_delivery_date__c)&lt;9),TEXT(0)&amp;TEXT(MONTH(WOO_Requested_delivery_date__c)),TEXT(MONTH(WOO_Requested_delivery_date__c))) &amp; 
IF(AND(DAY(WOO_Requested_delivery_date__c)&gt;0,DAY(WOO_Requested_delivery_date__c)&lt;9),TEXT(0)&amp;TEXT(DAY(WOO_Requested_delivery_date__c)),TEXT(DAY(WOO_Requested_delivery_date__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Requested delivery date sap format</label>
    <type>Text</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_Shipment_number__c.field-meta.xml
<CustomField>
    <fullName>WOO_Shipment_number__c</fullName>
    <label>Shipment number</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/wow/wmf_order/objects/WOO_WMF_Orders__c/fields/WOO_WMF_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>WOO_WMF_Order_Number__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Number</label>
    <type>Text</type>
</CustomField>

force-app/wow/wmf_order/classes/WOO_OrderCreateWrapper.cls
public with sharing class WOO_OrderCreateWrapper {
    @TestVisible
    private static Integer numberOfCharacters(Map<String, Integer> mapSAPfieldSize) {
        List<integer> i = mapSAPfieldSize.values();
        Integer sum = 0;
        for (integer j : i) {
            sum = sum + j;
        }
        return sum;
    }

    @TestVisible
    public static String formatFieldValue(String fieldValue, Integer maxLength) {
        if (fieldValue.length() >= maxLength) {
            return fieldValue.left(maxLength);
        } else {
            String spaceString = '';
            for (Integer i = 1; i <= maxLength - fieldValue.length(); i++) {
                spaceString = spaceString + ' ';
            }
            return fieldValue + spaceString;
        }
    }

    public class Header {
        public String headerLine {
            get {
                return headerLine == null ? '' : headerline;
            }
            private set;
        }
        public Map<String, Integer> mapSAPfieldSize = new Map<String, Integer>{
            'SART' => 3,
            'AUART' => 4,
            'VBELN' => 10,
            'VKORG' => 4,
            'KNDNR' => 10,
            'KUNWE' => 10,
            'KUNRG' => 10,
            'KUNRE' => 10,
            'BSTKD' => 35,
            'BSTDK' => 8,
            'ANRAG' => 35,
            'NA1AG' => 35,
            'NA2AG' => 35,
            'NA3AG' => 35,
            'NA4AG' => 35,
            'PLZAG' => 10,
            'ORTAG' => 35,
            'STRAG' => 35,
            'HNUAG' => 10,
            'EMAILAG' => 60,
            'ANRWE' => 35,
            'NA1WE' => 35,
            'NA2WE' => 35,
            'NA3WE' => 35,
            'NA4WE' => 35,
            'PLZWE' => 10,
            'ORTWE' => 35,
            'STRWE' => 35,
            'HNUWE' => 10,
            'EMAILWE' => 60,
            'ANRRE' => 35,
            'NA1RE' => 35,
            'NA2RE' => 35,
            'NA3RE' => 35,
            'NA4RE' => 35,
            'PLZRE' => 10,
            'ORTRE' => 35,
            'STRRE' => 35,
            'HNURE' => 10,
            'EMAILRE' => 60,
            'ANRRG' => 35,
            'NA1RG' => 35,
            'NA2RG' => 35,
            'NA3RG' => 35,
            'NA4RG' => 35,
            'PLZRG' => 10,
            'ORTRG' => 35,
            'STRRG' => 35,
            'HNURG' => 10,
            'EMAILRG' => 60,
            'KOMPV' => 1,
            'VERTR4' => 8,
            'ZZSNDNR' => 35
        };
        List<String> sapFields = new List<String>(mapSAPfieldSize.keySet());

        public Header() {
            for (integer i = 0; i < numberOfCharacters(this.mapSAPfieldSize); i++) {
                this.headerLine = this.headerLine + ' ';
            }
        }

        public void fillHeader(Case c, WOO_WMF_Orders__c order) {
            fillHeaderWithFixedValues(order);
            fillHeaderWithData(c, order);
        }

        @TestVisible
        private void fillHeaderWithFixedValues(WOO_WMF_Orders__c order) {
            String orderType = '';
            switch on order.WOO_Order_Type__c {
                when 'Finished products' {
                    orderType = 'K1TA';
                }
                when 'Spare part' {
                    orderType = 'K1TS';
                }
                when 'Repair' {
                    orderType = 'K1RR';
                }
            }
            this.headerline = 'AKO' + this.headerline.right(this.headerline.length() - 3);
            this.headerline =
                this.headerline.left(3) +
                orderType +
                this.headerline.right(this.headerline.length() - 7);
        }

        private void fillHeaderWithData(Case c, WOO_WMF_Orders__c order) {
            Map<String, String> mapSAPsalesforce = new Map<String, String>{
                'VBELN' => 'CaseNumber',
                'VKORG' => 'WOO_Commercial_organization__c',
                'KNDNR' => 'WOO_CPD_client_code__c',
                'KUNWE' => 'WOO_CPD_client_code__c',
                'KUNRE' => 'WOO_CPD_client_code__c',
                'KUNRG' => 'WOO_CPD_client_code__c',
                'BSTKD' => 'WOO_WMF_Order_Number__c',
                'BSTDK' => 'WOO_Requested_delivery_date_sap_format__c',
                'ANRAG' => 'Salutation',
                'NA1AG' => 'Name',
                'PLZAG' => 'WOO_Account_Postal_Code__c',
                'ORTAG' => 'WOO_Account_City__c',
                'STRAG' => 'WOO_Account_Street__c',
                'EMAILAG' => 'PersonEmail',
                'ANRWE' => 'Salutation',
                'NA1AG' => 'Name',
                'PLZWE' => 'WOO_Account_Postal_Code__c',
                'ORTWE' => 'WOO_Account_City__c',
                'STRWE' => 'WOO_Account_Street__c',
                'EMAILWE' => 'PersonEmail',
                'ANRRE' => 'Salutation',
                'NA1RE' => 'Name',
                'PLZRE' => 'WOO_Account_Postal_Code__c',
                'ORTRE' => 'WOO_Account_City__c',
                'STRRE' => 'WOO_Account_Street__c',
                'EMAILRE' => 'PersonEmail',
                'ANRRG' => 'Salutation',
                'NA1RG' => 'Name',
                'PLZRG' => 'WOO_Account_Postal_Code__c',
                'ORTRG' => 'WOO_Account_City__c',
                'STRRG' => 'WOO_Account_Street__c',
                'EMAILRG' => 'PersonEmail',
                'ZZSNDNR' => 'WOO_Shipment_number__c'
            };
            Integer indexPositionInHeaderline = 7;

            for (Integer j = 2; j < sapFields.size(); j++) {
                Integer fieldLength = mapSAPfieldSize.get(sapFields[j]);
                String fieldName = mapSAPsalesforce.get(sapFields[j]);
                String fieldValue = getFieldsValues(fieldName, c, order);
                if (fieldValue == null) {
                    indexPositionInHeaderline = indexPositionInHeaderline + fieldLength;
                    continue;
                } else {
                    String fieldToInsert = WOO_OrderCreateWrapper.formatFieldValue(
                        fieldValue,
                        fieldLength
                    );
                    this.headerLine =
                        this.headerLine.left(indexPositionInHeaderline) +
                        fieldToInsert +
                        this.headerline.right(
                            this.headerLine.length() - (indexPositionInHeaderline + fieldLength)
                        );
                    indexPositionInHeaderline = indexPositionInHeaderline + fieldLength;
                }
            }
        }

        private String getFieldsValues(String fieldName, Case c, WOO_WMF_Orders__c order) {
            String fieldValue;
            Map<String, Object> orderFieldsValues = order.getPopulatedFieldsAsMap();
            Map<String, Object> caseFieldsValues = c.getPopulatedFieldsAsMap();
            Account acc = (Account) caseFieldsValues.get('Account');
            Map<String, Object> accountFieldsValues = acc.getPopulatedFieldsAsMap();
            if (accountFieldsValues.containsKey(fieldName)) {
                // The account map must be parsed before the order map because of the duplicate key "Name"
                fieldValue = '' + accountFieldsValues.get(fieldName);
            } else if (orderFieldsValues.containsKey(fieldName)) {
                fieldValue = '' + orderFieldsValues.get(fieldName);
            } else if (caseFieldsValues.containsKey(fieldName)) {
                fieldValue = '' + caseFieldsValues.get(fieldName);
            }
            return fieldValue;
        }
    }

    public class OrderLine {
        public String orderLine {
            get {
                return orderLine == null ? '' : orderLine;
            }
            private set;
        }
        public Map<String, Integer> mapSAPfieldSize = new Map<String, Integer>{
            'SART' => 3,
            'VBELN' => 10,
            'BSTKD' => 35,
            'MATNR' => 18,
            'MENGE' => 14,
            'POSNR' => 6,
            'POTYP' => 4,
            'PREIS' => 14,
            'PEINH' => 14,
            'LGORT' => 4,
            'Wunschlieferdatum' => 10,
            'ZUORD' => 3,
            'FEORT' => 3,
            'FEART' => 3,
            'RPINS' => 3
        };
        List<String> sapFields = new List<String>(mapSAPfieldSize.keySet());

        public OrderLine() {
            for (integer i = 0; i < numberOfCharacters(this.mapSAPfieldSize); i++) {
                this.orderLine = this.orderLine + ' ';
            }
        }

        public void fillOrderLine(WOO_WMF_Order_Line_Item__c orderLineItem) {
            fillOrderLineWithFixedValues();
            fillOrderLineWithData(orderLineItem);
        }

        private void fillOrderLineWithFixedValues() {
            this.orderLine = 'APO' + this.orderLine.right(this.orderLine.length() - 3);
        }

        private void fillOrderLineWithData(WOO_WMF_Order_Line_Item__c orderLineItem) {
            Map<String, String> mapSAPsalesforce = new Map<String, String>{
                'VBELN' => 'WOO_WMF_Order_Number__c',
                'BSTKD' => 'WOO_WMF_Order_Number__c',
                'MATNR' => 'WOO_Product_CMMF__c',
                'MENGE' => 'WOO_Requested_quantity__c',
                'ZUORD' => 'WOO_Assigment__c',
                'FEORT' => 'WOO_Defect_Location__c',
                'FEART' => 'WOO_Defect_type__c',
                'RPINS' => 'WOO_Repair_instructions__c'
            };
            Integer indexPositionInOrderline = 3;

            for (Integer j = 1; j < sapFields.size(); j++) {
                Integer fieldLength = mapSAPfieldSize.get(sapFields[j]);
                String fieldName = mapSAPsalesforce.get(sapFields[j]);
                String fieldValue = getFieldsValues(fieldName, orderLineItem);
                if (fieldValue == null) {
                    indexPositionInOrderline = indexPositionInOrderline + fieldLength;
                    continue;
                } else {
                    String fieldToInsert = WOO_OrderCreateWrapper.formatFieldValue(
                        fieldValue,
                        fieldLength
                    );
                    this.orderLine =
                        this.orderLine.left(indexPositionInOrderline) +
                        fieldToInsert +
                        this.orderLine.right(
                            this.orderLine.length() - (indexPositionInOrderline + fieldLength)
                        );
                    indexPositionInOrderline = indexPositionInOrderline + fieldLength;
                }
            }
        }

        private String getFieldsValues(String fieldName, WOO_WMF_Order_Line_Item__c orderLineItem) {
            String fieldValue;
            Map<String, Object> orderLineItemFieldsValues = orderLineItem.getPopulatedFieldsAsMap();
            WOO_WMF_Orders__c order = (WOO_WMF_Orders__c) orderLineItemFieldsValues.get(
                'WOO_WMF_Order__r'
            );
            Map<String, Object> orderFieldsValues = order.getPopulatedFieldsAsMap();
            if (orderFieldsValues.containsKey(fieldName)) {
                fieldValue = '' + orderFieldsValues.get(fieldName);
            } else if (orderLineItemFieldsValues.containsKey(fieldName)) {
                fieldValue = '' + orderLineItemFieldsValues.get(fieldName);
            }
            return fieldValue;
        }
    }

    public class HeaderText {
        public String headerText {
            get {
                return headerText == null ? '' : headerText;
            }
            private set;
        }
        public Map<String, Integer> mapSAPfieldSize = new Map<String, Integer>{
            'SART' => 3,
            'VBELN' => 10,
            'BSTKD' => 35,
            'POSNR' => 6,
            'TEXT' => 70
        };
        List<String> sapFields = new List<String>(mapSAPfieldSize.keySet());

        public HeaderText() {
            for (integer i = 0; i < numberOfCharacters(this.mapSAPfieldSize); i++) {
                this.headerText = this.headerText + ' ';
            }
        }

        public void fillHeaderText(WOO_WMF_Orders__c order) {
            fillHeaderTextWithFixedValues();
            fillHeaderTextWithData(order);
        }

        private void fillHeaderTextWithFixedValues() {
            this.headerText = 'ATX' + this.headerText.right(this.headerText.length() - 3);
            String posnr = WOO_OrderCreateWrapper.formatFieldValue('0000', 6);
            this.headerText =
                this.headerText.left(48) +
                posnr +
                this.headerText.right(this.headerText.length() - 54);
        }

        private void fillHeaderTextWithData(WOO_WMF_Orders__c order) {
            Map<String, String> mapSAPsalesforce = new Map<String, String>{
                'VBELN' => 'WOO_WMF_Order_Number__c',
                'TEXT' => 'WOO_Comment__c'
            };
            Integer indexPositionInHeaderText = 3;

            for (Integer j = 1; j < sapFields.size(); j++) {
                Integer fieldLength = mapSAPfieldSize.get(sapFields[j]);
                String fieldName = mapSAPsalesforce.get(sapFields[j]);
                String fieldValue = getFieldsValues(fieldName, order);
                if (fieldValue == null) {
                    indexPositionInHeaderText = indexPositionInHeaderText + fieldLength;
                    continue;
                } else {
                    String fieldToInsert = WOO_OrderCreateWrapper.formatFieldValue(
                        fieldValue,
                        fieldLength
                    );
                    this.headerText =
                        this.headerText.left(indexPositionInHeaderText) +
                        fieldToInsert +
                        this.headerText.right(
                            this.headerText.length() - (indexPositionInHeaderText + fieldLength)
                        );
                    indexPositionInHeaderText = indexPositionInHeaderText + fieldLength;
                }
            }
        }

        private String getFieldsValues(String fieldName, WOO_WMF_Orders__c order) {
            String fieldValue;
            Map<String, Object> orderFieldsValues = order.getPopulatedFieldsAsMap();
            if (orderFieldsValues.containsKey(fieldName)) {
                fieldValue = '' + orderFieldsValues.get(fieldName);
            }
            return fieldValue;
        }
    }

    public class OrderText {
        public String orderText {
            get {
                return orderText == null ? '' : orderText;
            }
            private set;
        }
        public Map<String, Integer> mapSAPfieldSize = new Map<String, Integer>{
            'SART' => 3,
            'VBELN' => 10,
            'BSTKD' => 35,
            'POSNR' => 6,
            'TEXT' => 70
        };
        List<String> sapFields = new List<String>(mapSAPfieldSize.keySet());

        public OrderText() {
            for (integer i = 0; i < numberOfCharacters(this.mapSAPfieldSize); i++) {
                this.orderText = this.orderText + ' ';
            }
        }

        public void fillOrderText(WOO_WMF_Order_Line_Item__c orderLineItem) {
            fillOrderTextWithFixedValues();
            fillOrderTextWithData(orderLineItem);
        }

        private void fillOrderTextWithFixedValues() {
            this.orderText = 'ATX' + this.orderText.right(this.orderText.length() - 3);
            String posnr = WOO_OrderCreateWrapper.formatFieldValue('0', 6);
            this.orderText =
                this.orderText.left(48) +
                posnr +
                this.orderText.right(this.orderText.length() - 54);
        }

        private void fillOrderTextWithData(WOO_WMF_Order_Line_Item__c orderLineItem) {
            Map<String, String> mapSAPsalesforce = new Map<String, String>{
                'VBELN' => 'WOO_WMF_Order_Number__c',
                'TEXT' => 'WOO_Comment__c'
            };
            Integer indexPositionInOrderText = 3;

            for (Integer j = 1; j < sapFields.size(); j++) {
                Integer fieldLength = mapSAPfieldSize.get(sapFields[j]);
                String fieldName = mapSAPsalesforce.get(sapFields[j]);
                String fieldValue = getFieldsValues(fieldName, orderLineItem);
                if (fieldValue == null) {
                    indexPositionInOrderText = indexPositionInOrderText + fieldLength;
                    continue;
                } else {
                    String fieldToInsert = WOO_OrderCreateWrapper.formatFieldValue(
                        fieldValue,
                        fieldLength
                    );
                    this.orderText =
                        this.orderText.left(indexPositionInOrderText) +
                        fieldToInsert +
                        this.orderText.right(
                            this.orderText.length() - (indexPositionInOrderText + fieldLength)
                        );
                    indexPositionInOrderText = indexPositionInOrderText + fieldLength;
                }
            }
        }

        private String getFieldsValues(String fieldName, WOO_WMF_Order_Line_Item__c orderLineItem) {
            String fieldValue;
            Map<String, Object> orderLineItemFieldsValues = orderLineItem.getPopulatedFieldsAsMap();
            WOO_WMF_Orders__c order = (WOO_WMF_Orders__c) orderLineItemFieldsValues.get(
                'WOO_WMF_Order__r'
            );
            Map<String, Object> orderFieldsValues = order.getPopulatedFieldsAsMap();
            if (orderFieldsValues.containsKey(fieldName)) {
                fieldValue = '' + orderFieldsValues.get(fieldName);
            } else if (orderLineItemFieldsValues.containsKey(fieldName)) {
                fieldValue = '' + orderLineItemFieldsValues.get(fieldName);
            }
            return fieldValue;
        }
    }
}